# Generated by Django 3.2.8 on 2021-10-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('deadline', models.CharField(max_length=50)),
                ('priority', models.CharField(choices=[('HP', 'High Priority'), ('MP', 'Medium Priority'), ('LP', 'Low Priority')], default='MP', max_length=2)),
                ('user', models.CharField(max_length=50)),
            ],
        ),
    ]
